### ISSUE TITLE
Do you have an example, running Playwright and Jest for e2e Angular tests but Karma for Unit Tests? I have been trying to make this work for a while, but I have been unsuccessful. Thanks

### ISSUE THREAD

**Issue by dcleve333** [playwright-community/playwright-jest-examples#18] opened 2021-02-07 06:19 UTC

**Comment by mxschmitt** [comment] 2021-02-09 22:41
Duplicate of that https://stackoverflow.com/questions/66085172/does-anyone-have-an-example-for-running-playwright-and-jest-for-e2e-angular-test

**Closed by mxschmitt** 2021-02-09 22:41 UTC
